[[language]]
name = "go"
formatter = { command = "gofmt" }
auto-format = true
language-servers = ["gopls", "golangci-lint-lsp"]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path", "stdout", "--show-stats=false", "--issues-exit-code=1"]
